env:
  global:
    - CC_TEST_REPORTER_ID=bef4813a0c7431f6389f12651bbab50c345c22ff03e737afdfcad090a27b9c85

language: php

php:
  - 7.2.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS SOEN341SC4;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

  # Code Climate testing requirements
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
  - chmod +x ./cc-test-reporter 
  - ./cc-test-reporter before-build

script:
  - php artisan key:generate

  # Assure databases are setup and seeded
  - php artisan migrate
<<<<<<< HEAD
=======
  - php artisan migrate --path=/database/migrations/qa
>>>>>>> test_rz2
  - php artisan db:seed

  # Testing and code coverage
  - vendor/bin/phpunit --testsuite=Unit --coverage-text --coverage-clover "clover.xml"

after_script:
  # Testing and code coverage
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

