env:
  global:
    - CC_TEST_REPORTER_ID=bef4813a0c7431f6389f12651bbab50c345c22ff03e737afdfcad090a27b9c85

language: php

php:
  - 7.2.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS SOEN341SC4;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install jest

  # Download code climate binaries and set proper permissions
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
  - chmod +x ./cc-test-reporter 

  # Notify code climate of an incoming coverage payload
  - ./cc-test-reporter before-build

script:
  - php artisan key:generate

  # Assure databases are setup and seeded
  - php artisan migrate
  - php artisan migrate --path=database/migrations/q-a
  - php artisan db:seed

  # Run php tests. 
  # Test output ./tests/test_output/php/clover.xml -> partial-formatting ./tests/coverage/codeclimate.php_coverage.json
  - vendor/bin/phpunit --testsuite=Unit --coverage-text --coverage-clover "tests/test_output/php/clover.xml"
  - ./cc-test-reporter format-coverage --input-type clover --output "coverage/codeclimate.php_coverage.json" tests/test_output/php/clover.xml

  # Run react tests. 
  # Test output ./tests/test_output/react/clover.xml -> partial-formatting ./tests/coverage/codeclimate.react_coverage.json
  - npm test
  - ./cc-test-reporter format-coverage --input-type clover --output "coverage/codeclimate.react_coverage.json" tests/test_output/react/clover.xml

after_script:
  # Sum the partial coverage files outputs coverage/codeclimate.json
  - ./cc-test-reporter sum-coverage --parts 2 coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage
